### ISSUE TITLE
Line 572 produces error

### ISSUE THREAD

**Issue by ThomasSultana** [Lipseys/LipseysApiIntegrationPhp#3]
Hi line 572 contains the following in 1.4 

`if(!$this["Token"]){`

Can we get this changed to 

`if(!$this->Token){`

Thank you

**Comment by jawetzel** [comment]
Resolved in commit 1.1.5

https://github.com/Lipseys/LipseysApiIntegrationPhp/commit/88729d9dcf907fafdc6064af0311386683126fa9
